# Generated by Django 2.1.4 on 2018-12-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='date_added',
        ),
    ]
