# Generated by Django 2.1.4 on 2018-12-11 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0002_auto_20181211_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 11, 22, 30, 45, 702414)),
        ),
    ]
